[package]
name = "iv2cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
crossbeam-channel = "0.5.15"
crossterm = "0.29.0"
iv2c = { path = "../iv2c" }
